"""
BART_30cm_NAIP_TrainModel.py
----------------------------
Fine-tunes a pretrained DeepForest tree crown detection model on hand-annotated
NAIP imagery at 30 cm resolution for the Bartlett Experimental Forest (BART) site.

Workflow:
    1. Load the pretrained DeepForest release model
    2. Point training config to annotations CSV produced by developTrainingData.R
    3. Fine-tune the model using PyTorch Lightning trainer
    4. Verify checkpoint save/reload integrity using a sample crop image
    5. Save final model weights to a named .pt file

Inputs (produced upstream by developTrainingData.R):
    - ./Imagery/NAIP/Training/Crop_Images/annotations.csv
    - Crop image .tif files listed in annotations.csv

Outputs:
    - ./TrainedModels/NAIP_30cm_BART_trained.pt   (model weights)

Notes:
    - Full tile inference is handled downstream by BART_30cm_NAIP_Trained.py
    - Training annotations were generated by developTrainingData.R using QGIS
      bounding boxes overlaid on NAIP imagery with NEON LiDAR for visual guidance
"""

# =============================================================================
# Dependencies
# =============================================================================
import os
import tempfile

import torch
import pandas as pd

from deepforest import main   # Core DeepForest model class

# =============================================================================
# Configuration — edit these variables to adapt script to a new site/product/res
# =============================================================================
os.chdir('/fs/ess/PUOM0017/ForestScaling/DeepForest')

SITE    = "BART"    # Site code (e.g. BART, HARV) — included in output model filename
PRODUCT = "NAIP"    # Imagery source (e.g. NAIP, NEON, MAXAR)
RES     = 0.3       # Spatial resolution in meters
RES_CM  = int(RES * 100)   # Resolution as integer cm (e.g. 0.3 → 30); used in filenames
EPOCHS  = 50        # Number of training epochs (5–10 sufficient when fine-tuning from release)

# =============================================================================
# Load pretrained DeepForest model
# =============================================================================
# Start from the published release model (trained on NEON 10cm RGB across the US)
# and fine-tune on local NAIP annotations. This transfer learning approach avoids
# training from scratch and typically converges in far fewer epochs.
prebuilt_model = main.deepforest()
prebuilt_model.use_release()

# =============================================================================
# Locate training annotations
# =============================================================================
# annotations.csv is produced by developTrainingData.R, which:
#   - Crops NAIP tiles to manually annotated bounding box regions (drawn in QGIS)
#   - Converts bounding box coordinates from UTM to image pixel space
#   - Writes one row per tree crown with columns: image_path, xmin, ymin, xmax, ymax, label
# image_path values in the CSV are relative to crop_dir (not absolute paths).
crop_dir         = "./Imagery/NAIP/Training/Crop_Images/"
annotations_file = os.path.join(crop_dir, "annotations.csv")

assert os.path.exists(annotations_file), \
    f"Annotations file not found: {annotations_file}. Run developTrainingData.R first."

# Read annotations to extract a sample crop image for post-training verification
annotations_df = pd.read_csv(annotations_file)
sample_image   = os.path.join(crop_dir, annotations_df["image_path"].iloc[0])

# =============================================================================
# Configure and run training
# =============================================================================
# Set all config options before calling create_trainer() — the trainer reads
# these values at instantiation and changes made after will not take effect.

prebuilt_model.config["epochs"]          = EPOCHS
prebuilt_model.config["save-snapshot"]   = False   # Disable intermediate snapshots

# Point trainer to the annotations CSV and the directory containing crop images
prebuilt_model.config["train"]["csv_file"] = annotations_file
prebuilt_model.config["train"]["root_dir"] = os.path.dirname(annotations_file)

# fast_dev_run: set True only for debugging (runs 1 batch to verify the pipeline)
# Must be set BEFORE create_trainer() — the flag is read at trainer instantiation
prebuilt_model.config["train"]["fast_dev_run"] = False

# Instantiate the PyTorch Lightning trainer using the config above
prebuilt_model.create_trainer(max_epochs=EPOCHS)

# Fine-tune the model. trainer.fit() calls the model on itself per Lightning convention.
prebuilt_model.trainer.fit(prebuilt_model)

# =============================================================================
# Checkpoint verification
# =============================================================================
# Confirm that the trained model can be saved to and reloaded from a checkpoint
# without loss of predictions. Uses a small crop image (not a full tile) as the
# test input, which is appropriate for predict_image(). Full tile inference using
# predict_tile() is handled in BART_30cm_NAIP_Trained.py.
pred_after_train = prebuilt_model.predict_image(path=sample_image)

tmpdir = tempfile.TemporaryDirectory()
prebuilt_model.trainer.save_checkpoint(f"{tmpdir.name}/checkpoint.ckpt")

after            = main.deepforest.load_from_checkpoint(f"{tmpdir.name}/checkpoint.ckpt")
pred_after_reload = after.predict_image(path=sample_image)

# Verify predictions are non-empty and identical after save/reload
try:
    assert not pred_after_train.empty,   "No predictions after training — check annotations and score_threshold"
    assert not pred_after_reload.empty,  "No predictions after reload — checkpoint may be corrupt"
    pd.testing.assert_frame_equal(pred_after_train, pred_after_reload)
    print("Checkpoint verification passed.")
except AssertionError as e:
    print(f"WARNING: Checkpoint verification failed: {e}")
    print("Model weights will still be saved. Review predictions manually.")

# =============================================================================
# Save final model weights
# =============================================================================
# Save the model's state dict (weights only, not the full Lightning module).
# Filename encodes product, resolution, and site for unambiguous identification
# across multi-site and multi-resolution runs.
# Loaded downstream with: model.model.load_state_dict(torch.load(model_path))
model_path = f"./TrainedModels/{PRODUCT}_{RES_CM}cm_{SITE}_trained.pt"
os.makedirs(os.path.dirname(model_path), exist_ok=True)
torch.save(prebuilt_model.model.state_dict(), model_path)

print(f"Model saved to: {model_path}")
